# Numpy

## 导入Numpy库

In [2]:
import numpy as np

## N维数组

### 创建一个数组

In [3]:
array_1 = np.array([1, 2, 3])
print('array_1 :\n', array_1)
array_2 = np.array([[6, 2], [2, 3], [8, 5]])
print('array_2 :\n', array_2)

array_1 :
 [1 2 3]
array_2 :
 [[6 2]
 [2 3]
 [8 5]]


In [17]:
# 指定tarray_1的最小维度
tarray_1 = np.array([1, 2, 3], ndmin = 2)
print('tarray_1：', tarray_1)
# 指定tarray_2的类型为复数类型
tarray_2 = np.array([1, 3, 4], dtype=complex)
print('tarray_2：', tarray_2)

tarray_1： [[1 2 3]]
tarray_2： [1.+0.j 3.+0.j 4.+0.j]


## 创建指定元素的数组

In [19]:
earray_1 = np.empty([5, 8])    # 创建元素为空的数组
print('earray_1:', earray_1)
zarray_1 = np.zeros([5, 8])   # 创建元素为0的数组
print('zarray_1:',zarray_1)
oarray_1 = np.ones([5, 8])   # 创建元素为1的数组
print('oarray_1:', oarray_1)

earray_1: [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
zarray_1: [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
oarray_1: [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [21]:
cpzarray_1 = np.zeros_like(array_1)   # 创建与array_1大小相同且元素为0的数组
print("cpzarray_1", cpzarray_1)
cpoarray_1 = np.ones_like(array_2)   # 创建与array_2大小相同且元素为1的数组
print('cpoarray_1', cpoarray_1)

cpzarray_1 [0 0 0]
cpoarray_1 [[1 1]
 [1 1]
 [1 1]]


### N维度数组的属性

In [14]:
array_3 = np.array([[1, 2], [2, 3]])
print("shape :", array_3.shape)  # 查看维度
print("dtype :", array_3.dtype)  # 查看数据类型
print("size :", array_3.size)   # 查看元素个数

shape : (2, 2)
dtype : int32
size : 4


In [16]:
print("array_3:", array_3.reshape(4, ))   # 原数组不发生改变
print("array_3:", array_3)
array_3.shape = (4)     # 原数组发生改变
print("array_3:", array_3)

array_3: [1 2 2 3]
array_3: [[1 2]
 [2 3]]
array_3: (4,)
array_3: [1 2 2 3]


### 索引与切片

In [22]:
array_4 = np.array([[1, 2], [3, 4]])
print('array_4[0, 0] :', array_4[0, 0])  # 第0行第0列的元素
print('array_4[0, :] :', array_4[0, :])  # 第0行的所有元素
print('array_4[:, 0] :', array_4[:, 0])  # 第0列的所有元素

array_4[0, 0] : 1
array_4[0, :] : [1 2]
array_4[:, 0] : [1 3]


### 简单的数学运算

In [21]:
array_5 = np.array([1, 2, 3])
array_6 = np.array([4, 5, 6])
print('array_5 + array_6 :', array_5 + array_6)   # 对应元素相加
print('array_5 * array_6 :', array_5 * array_6)   # 对应元素相乘

array_5 + array_6 : [5 7 9]
array_5 * array_6 : [ 4 10 18]


### 数组的广播

In [26]:
array_7 = np.array([[1, 2], [3, 4]])
array_8 = np.array([1, 2])
print('array_7 + array_8 :\n', array_7 + array_8)   # 会自动调整大小,将维度较低的进行直接赋值扩大

array_7 + array_8 :
 [[2 4]
 [4 6]]


In [58]:
tarray_7 = np.linspace(0, 50, 16)
tarray_7.shape = (2, 2, 4)
print('tarray_7:\n', tarray_7)
tarray_8 = np.linspace(1, 10, 4)
# tarray_8.shape = (4)
print('tarray_8:\n', tarray_8)
print('tarray_8 + tarray_7:\n',tarray_8 + tarray_7)

tarray_7:
 [[[ 0.          3.33333333  6.66666667 10.        ]
  [13.33333333 16.66666667 20.         23.33333333]]

 [[26.66666667 30.         33.33333333 36.66666667]
  [40.         43.33333333 46.66666667 50.        ]]]
tarray_8:
 [ 1.  4.  7. 10.]
tarray_8 + tarray_7:
 [[[ 1.          7.33333333 13.66666667 20.        ]
  [14.33333333 20.66666667 27.         33.33333333]]

 [[27.66666667 34.         40.33333333 46.66666667]
  [41.         47.33333333 53.66666667 60.        ]]]


### 数组的切片和转置

In [31]:
array_9 = np.array([[1, 2, 3], [4, 5, 6]])
print('array_9[0, :2] :\n', array_9[0, :2])  # 第0行中前两个元素
print('array_9[:, 1:] :\n', array_9[:, 1:])  # 第1列到最后一列的所有元素

array_9[0, :2] :
 [1 2]
array_9[:, 1:] :
 [[2 3]
 [5 6]]


### 数组的排序和搜索

In [33]:
array_10 = np.array([3, 1, 4, 1, 5, 9])
print('排序后的数组：', np.sort(array_10))  # 进行正序排序
print('排序后的索引位置为：', np.argsort(array_10))   # 排序后的索引位置
print('数组中最小值的索引对应的值为： ', array_10[np.argmin(array_10)])  # 搜索数组中的最小值
print('数组中最大值的索引对应的值为：', array_10[np.argmax(array_10)])  # 搜索数组中的最大值

排序后的数组： [1 1 3 4 5 9]
排序后的索引位置为： [1 3 0 2 4 5]
数组中最小值的索引为：  1
数组中最大值的索引为： 9


### 数组的统计函数

In [35]:
array_11 = np.array([1, 2, 3, 4, 5])
print('均值：', np.mean(array_11))   # 数组中的均值
print('方差：', np.std(array_11))   # 数组中的方差
print('标准差：', np.var(array_11))   # 数组中的标准差
print('最大值：', np.max(array_11))   # 数组中的最大值
print('最小值：', np.min(array_11))   # 数组中的最小值

均值： 3.0
方差： 1.4142135623730951
标准差： 2.0
最大值： 5
最小值： 1


## 四种乘法对比解析

**对于数组a和b有以下四种乘法：**
1. `a * b`: 数组中的对应元素相乘。
2. `np.multiply(a, b)`: 等价于`a * b`。
3. `a @ b`: 矩阵的标准乘法。
4. `np.dot(a, b)`:等价于`a @ b`。

In [37]:
array_12 = np.array([[1, 2], [3, 4]])
array_13 = np.array([[5, 6], [7, 8]])
print('array_12 @ array_13： \n', array_12 @ array_13)
print('np.dot(array_12, array_13)：\n', np.dot(array_12, array_13))
print('array_12 * array_13：\n', array_12 * array_13)
print('np.multiply(array_12, array_13)：\n', np.multiply(array_12, array_13))

array_12 @ array_13： 
 [[19 22]
 [43 50]]
np.dot(array_12, array_13)：
 [[19 22]
 [43 50]]
array_12 * array_13：
 [[ 5 12]
 [21 32]]
np.multiply(array_12, array_13)：
 [[ 5 12]
 [21 32]]


### Multiply的高级用法

In [52]:
array_14 = np.array([1, 2, 3, 4, 5])
array_15 = np.array([[1, 2, 3], [4, 5, 6]])

print('array_14累乘：', np.multiply.reduce(array_14))  # 对数组进行累乘
print('array_15累乘：', np.multiply.reduce(array_15))  # 对数组中的最后一个维度进行累成
print('array_14对应相乘：', np.multiply(array_14, np.array([1, 2, 3, 1, 1])))  # 两个数组中对应的数进行相乘
print('array_14.T广播相乘：\n', np.multiply(array_14.T, np.array([3]))) # 将数组进行转置，然后进行广播相乘
print('array_15广播相乘：\n', np.multiply(array_15, np.array([1, 2, 1])))  # 对数组进行广播相乘
print('array_15.T广播相乘：\n', np.multiply(array_15.T, np.array([1, 2])))  # 对数组转置后进行广播相乘

array_14累乘： 120
array_15累乘： [ 4 10 18]
array_14对应相乘： [1 4 9 4 5]
array_14.T广播相乘：
 [ 3  6  9 12 15]
array_15广播相乘：
 [[ 1  4  3]
 [ 4 10  6]]
array_15.T广播相乘：
 [[ 1  8]
 [ 2 10]
 [ 3 12]]


### Sum的高阶用法

In [55]:
array_16 = np.array([1, 2, 3, 4, 5])
array_17 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('array_16求和：', np.sum(array_16))
print('array_17求和：', np.sum(array_17))
print('array_16对第一维度求和：', np.sum(array_16, axis=0))
print('array_17第一维度求和：', np.sum(array_17, axis=0))
print('array_17第二维度求和：', np.sum(array_17, axis=1))

array_16求和： 15
array_17求和： 45
array_16对第一维度求和： 15
array_17第一维度求和： [12 15 18]
array_17第二维度求和： [ 6 15 24]


## 数组的迭代

In [52]:
array_17 = np.arange(10).reshape(2, 5)
print('array_17:', array_17)
for i in np.nditer(array_17):
    print(i, end=' ')
print()
for i in np.nditer(array_17, order = 'C'):  # 按行进行遍历
    print(i, end=' ')
print()
for i in np.nditer(array_17, order = 'F'):  # 按列进行遍历
    print(i, end=' ')

array_17: [[0 1 2 3 4]
 [5 6 7 8 9]]
0 1 2 3 4 5 6 7 8 9 
0 1 2 3 4 5 6 7 8 9 
0 5 1 6 2 7 3 8 4 9 

### 广播迭代

In [76]:
array_18 = np.arange(1, 9).reshape(2, 4)
array_19 = np.linspace(1, 10, 4).reshape(4)
print('array_18:', array_18)
print('array_19:', array_19)
for i, j in np.nditer([array_18, array_19]):
    print(i,':',j, end='\t')

array_18: [[1 2 3 4]
 [5 6 7 8]]
array_19: [ 1.  4.  7. 10.]
1 : 1.0	2 : 4.0	3 : 7.0	4 : 10.0	5 : 1.0	6 : 4.0	7 : 7.0	8 : 10.0	

## 插入轴

In [80]:
array_20 = np.array([[1, 2], [3, 4]])
print('array_20:\n', array_20)
print('array_20.shape:',array_20.shape)
array_21 = np.expand_dims(array_20, 0)
print('array_21:\n', array_21)
print('array_21.shape:',array_21.shape)

array_20:
 [[1 2]
 [3 4]]
array_20.shape: (2, 2)
array_21:
 [[[1 2]
  [3 4]]]
array_21.shape: (1, 2, 2)


## 删除轴

In [84]:
array_22 = np.arange(16).reshape(1, 4, 4)
print(array_22.shape)
array_23 = array_22.squeeze()
print(array_23.shape)

(1, 4, 4)
(4, 4)


## 连接数组

In [88]:
array_24 = np.arange(12).reshape(4, 3)
array_25 = np.arange(8, 20).reshape(4, 3)
print('array_24:\n', array_24)
print('array_25:\n', array_25)
array_concatenate = np.concatenate((array_24, array_25), axis = 1)  # 沿着轴1进行连接
print('array_concatenate:\n', array_concatenate)

array_24:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
array_25:
 [[ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
array_concatenate:
 [[ 0  1  2  8  9 10]
 [ 3  4  5 11 12 13]
 [ 6  7  8 14 15 16]
 [ 9 10 11 17 18 19]]


## 数组的切分

In [118]:
array_26 = np.arange(12).reshape(3, 4)
print('array_26:\n', array_26)
array_sp = np.split(array_26, [1, 2])
print('array_sp:\n', array_sp)

array_26:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array_sp:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


## 添加与删除元素

In [147]:
array_27 = np.arange(12).reshape(3, 4)
print('array_27:\n', array_27)
# 改变形状：
array_28 = np.resize(array_27, (4, 4))   # 重复了一行元素
print('array_28:\n', array_28)

# 添加元素
array_ap = np.append(array_27, [1, 1, 1])
print('array_ap:\n', array_ap)

array_ap0 = np.append(array_27, [[1, 1, 1, 1]], axis = 0)
print('array_ap0:\n', array_ap0)

# 插入元素
array_in = np.insert(array_27, 1, [[1, 1, 1, 1]], axis = 0)
print('array_in:\n', array_in)

# 删除元素
array_del = np.delete(array_27, 1, axis = 0)  # 删除第二行
print('array_del:\n', array_del)

# 去重
array_un = np.unique(array_27)
print('array_un:\n', array_un)

array_un = np.unique(array_27, return_index = True)  # 去重并返回在原数组中的下标
print('array_un:\n', array_un)

array_27:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array_28:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
array_ap:
 [ 0  1  2  3  4  5  6  7  8  9 10 11  1  1  1]
array_ap0:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 1  1  1  1]]
array_in:
 [[ 0  1  2  3]
 [ 1  1  1  1]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array_del:
 [[ 0  1  2  3]
 [ 8  9 10 11]]
array_un:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
array_un:
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64))
